/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#fffbff",
        "surface": "#fcf9f8",
        "on-error": "#ffffff",
        "tertiary-container": "#be552c",
        "inverse-on-surface": "#f3f0ef",
        "on-primary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        "secondary-container": "#bceecf",
        "on-surface-variant": "#57423b",
        "on-tertiary-container": "#fffbff",
        "surface-tint": "#a23e18",
        "primary-fixed-dim": "#ffb59c",
        "secondary-fixed": "#bceecf",
        "surface-container-highest": "#e5e2e1",
        "secondary": "#3a674f",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#390c00",
        "secondary-fixed-dim": "#a1d1b4",
        "primary-fixed": "#ffdbcf",
        "background": "#fcf9f8",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#1b1b1b",
        "surface-dim": "#dcd9d9",
        "on-secondary-fixed": "#002112",
        "surface-container": "#f0eded",
        "on-tertiary-fixed": "#380c00",
        "primary": "#9f3c16",
        "on-tertiary-fixed-variant": "#812901",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb59c",
        "on-surface": "#1b1b1b",
        "surface-variant": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#406d55",
        "tertiary-fixed": "#ffdbcf",
        "surface-container-high": "#eae7e7",
        "inverse-primary": "#ffb59c",
        "primary-container": "#bf542c",
        "outline-variant": "#dec0b7",
        "inverse-surface": "#313030",
        "error": "#ba1a1a",
        "tertiary": "#9e3d16",
        "on-primary-fixed-variant": "#822801",
        "on-secondary-fixed-variant": "#224f39",
        "outline": "#8a726a"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "gutter": "1rem",
        "margin-desktop": "2.5rem",
        "space-md": "1rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
